name: BARtab-env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.8
  - nextflow
  - R=4.1
  - r-tidyverse
  - fastqc
  - cutadapt
  - starcode
  - flash
  - fastx_toolkit
  - bowtie
  - samtools
