name: BARtab-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - nextflow
  - r-base
  - r-dplyr
  - r-purrr
  - r-ggplot2
  - r-magrittr
  - fastqc
  - cutadapt
  - starcode
  - flash
  - fastx_toolkit
  - bowtie
  - samtools
  - multiqc
