name: BARtab-environment
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9
  - nextflow
  - R=4.1
  - r-tidyverse
  - fastqc
  - cutadapt-1.18
  - starcode=1.4
  - flash=1.2.11
  - fastx-toolkit=0.0.14
  - bowtie=1.2
  - samtools=1.9
