use_filename_as_sample_name:
  - cutadapt

sample_names_ignore:
  - "command"
  - "command.err"

fn_clean_exts:
  - ".filter.log"
  - ".cutadapt.log"
  - ".bowtie.log"
  - ".fastq.gz"
  - "filtered"
  - "bowtie"

run_modules:
  - fastqc
  - cutadapt
  - bowtie1
  - starcode
  - flash

top_modules:
  - "fastqc"