use_filename_as_sample_name:
  - cutadapt
  - bowtie1

fn_clean_exts:
  - ".filter.log"
  - ".cutadapt_up.log"
  - ".cutadapt_down.log"
  - ".cutadapt_both.log"
  - ".bowtie.log"
  - ".fastq.gz"
  - ".hist"

sp:
  flash/hist:
    fn: "*.hist"

run_modules:
  - fastqc
  - cutadapt
  - bowtie1
  - flash

top_modules:
  - "fastqc"

module_order:
  - "fastqc"
  - "flash"
  - cutadapt:
        name: "Cutadapt (upstream)"
        anchor: "cutadapt_up"
        path_filters:
          - "*.cutadapt_up.log"
  - cutadapt:
        name: "Cutadapt (downstream)"
        anchor: "cutadapt_down"
        path_filters:
          - "*.cutadapt_down.log"
  - cutadapt:
        name: "Cutadapt (both up- and downstream)"
        anchor: "cutadapt_both"
        path_filters:
          - "*.cutadapt_both.log"
  - "bowtie1"